server:
  port: 5555

spring:
  application:
    name: subject-server
  data:
    mongodb:
      host: localhost
      port: 27017
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/