server:
  port: 5555

spring:
  application:
    name: subject-server
  data:
    mongodb:
      host: sub-mongo
      port: 27016
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/